apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-app-config
data:
  index.html: |
    <html>
      <body style="font-family: Arial;">
        <h1>Hello from ArgoCD </h1>
        <p>If you see this, GitOps works.</p>
      </body>
    </html>
