apiVersion: v1
kind: ConfigMap
metadata:
  name: wave-demo-config
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  index.html: |
    <html>
      <body style="font-family: Arial;">
        <h1>Sync Waves </h1>
        <p>ConfigMap applied before Deployment.</p>
      </body>
    </html>

